apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: bert-fine-tuning-pipeline2-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.22, pipelines.kubeflow.org/pipeline_compilation_time: '2024-03-06T15:36:42.231441',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "A pipeline that fine-tunes
      bert model with sprecific data.", "name": "bert Fine-Tuning Pipeline2"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.22}
spec:
  entrypoint: bert-fine-tuning-pipeline2
  templates:
  - name: bert-fine-tuning-pipeline2
    dag:
      tasks:
      - {name: data-preprocessing2, template: data-preprocessing2}
      - name: fine-tuned-model-evaluation2
        template: fine-tuned-model-evaluation2
        dependencies: [output-after-fine-tuning2]
      - name: output-after-fine-tuning2
        template: output-after-fine-tuning2
        dependencies: [data-preprocessing2]
      - name: output-before-fine-tuning2
        template: output-before-fine-tuning2
        dependencies: [data-preprocessing2]
  - name: data-preprocessing2
    container:
      args: [--dataset, ag_news, --split, 'train[:1%]']
      command: [python3, /app/Preprocess_data/preprocess_data.py]
      image: maamounm/llm_pipeline:latest
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: fine-tuned-model-evaluation2
    container:
      command: [python3, /app/evaluate_fine_tuned_model/evaluate_fine_tuned_model.py]
      image: maamounm/llm_pipeline:latest
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: output-after-fine-tuning2
    container:
      command: [python3, /app/Fine_tuned_model_output/fine_tuned_model_output.py]
      image: maamounm/llm_pipeline:latest
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: output-before-fine-tuning2
    container:
      command: [python3, /app/Model_output/model_output.py]
      image: maamounm/llm_pipeline:latest
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
